### ISSUE TITLE
Convertors for MySQLI

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/converters#1]
Convertors for MySQLI

Seems to fail with the handling at least on windows. Not sure how many now currently use ADO on windows.

Code such as
`	// Okay, the hardest is ADO (Windows only, by the way.)
	if (!is_resource($result) && is_object($result))
	{
		if ($result->EOF)
			return false;

		$row = array();
		$fields = $result->Fields;
		for ($i = 0, $n = $fields->Count; $i < $n; $i++)
		{
			$field = $fields[$i];
			$row[$field->Name] = $field->Value;
		}
		$result->MoveNext();

		return $row;
	}
`

**Comment by VBGAMER45** [comment]
Fixed in https://github.com/SimpleMachines/converters/commit/655e8bc2ac3cdcabd1511104b02117fb489b406e

**Comment by jdarwood007** [comment]
This is the wrong fix really.  birthdate column is not in the select so its not being converted, resulting in that not existing at all and that error.
