### ISSUE TITLE
Convertor issue Unknown system variable 'SQL_MAX_JOIN_SIZE'

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/converters#2]
Convertor issue Unknown system variable 'SQL_MAX_JOIN_SIZE
Saw this issue http://www.simplemachines.org/community/index.php?topic=551482.0

In convert.php for MySQL 5.6 and higher
The list of changes in MySQL 5.6 is at

http://dev.mysql.com/doc/refman/5.6/en/mysql-nutshell.html

Under Removed Features it says:

The sql_max_join_size system variable. Use max_join_size instead.

**Comment by VBGAMER45** [comment]
Added the MySQL version handling in this commit https://github.com/SimpleMachines/converters/commit/655e8bc2ac3cdcabd1511104b02117fb489b406e

**Comment by jdarwood007** [comment]
Wrong reference?  That commit has nothing to do with this.
Use "Fixes ####" in your commit messages and it will auto-link and close fixes.
