### ISSUE TITLE
 Converter Issue SMF 2.0.x when sessions fail 

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/converters#3]
If you can't write to the sessions path  the conversion can fail.
See this topic for details
https://www.simplemachines.org/community/index.php?topic=551406.0

**Comment by VBGAMER45** [comment]
Added a check if the session save path is writable in this commit https://github.com/SimpleMachines/converters/commit/655e8bc2ac3cdcabd1511104b02117fb489b406e

**Comment by jdarwood007** [comment]
Wrong reference here, doesn't look like this fixes that.
