### ISSUE TITLE
Move to MYSQLi for convert.php?

### ISSUE THREAD

**Issue by MisterVector** [SimpleMachines/converters#7]
So I wanted to convert a couple archived IPB 2.3 forums to SMF. My environment has PHP 7.3 and I noticed that the conversion PHP script only supports PHP 4 and 5. I noticed that the reason for this, at least from what I've seen, is because it relies on the MYSQL extension which was removed in PHP 7.0.0. I don't know of the implications of moving to MYSQLi for convert.php other than it would remove the support for PHP 4.

**Comment by VBGAMER45** [comment]
The convert.php found in this repo should support up to PHP 7.4 make sure you grab that along with .sql file from this repo and use that for conversion.

**Comment by MisterVector** [comment]
Oh, looks like I had the wrong version of this... sorry about this!
